### ISSUE TITLE
作成者が削除された予定の同期で例外が発生する

### ISSUE THREAD

**Issue by mrmt** [cybozu/garoon-google#2]
もう存在しないサイボウズユーザーが作成した予定を同期しようとすると、以下の例外が発生します。

```
 ERROR 13:14:17 For input string: ""
 java.lang.NumberFormatException: For input string: ""
      at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
```

github上の最新版 (Latest commit da87468  on 1 Nov 2016) でも再現しました。

もう存在しないサイボウズユーザーとは、たとえばガルーン上では

> 山田 一郎（削除されたユーザー）2017/02/14（火） 14:21

のように表示されるユーザーです。

退職した同僚が設定してくれたサイボウズ予定がある状態で、その退職者のアカウント消込が行われると、
GGsyncが失敗しだす、というのが起こりやすい状況でしょう。

手が空いたらコードを追ってみようと思いますが、取り急ぎご報告まで。

**Comment by cy-takeuchi** [comment]
ユーザーが削除されるとuser_idが取得できずに例外が発生していました。

・削除前
 <creator user_id="68" name="take2" date="2017-03-31T07:08:59Z" />

・削除後
 <creator  name="take2" date="2017-03-31T07:08:59Z" />

**Comment by mrmt** [comment]
現象が発生したのと同じ状況で、問題が再現しないことを確認できました。
どうもありがとうございました!
